philly: True
tarfile: True
model: "childnet"
batch_size: 128
sched: "cosine"
epochs: 500
decay_epochs: 2.4
decay_rate: 0.973
opt: "rmsproptf"
opt_eps: 0.001
j: 8
warmup_lr: 1.0e-6
weight_decay: 1.0e-5
drop: 0.2
model_ema: True
model_ema_decay: 0.9999
aa: "rand-m9-mstd0.5"
remode: "pixel"
reprob: 0.2
lr: 0.064
num_classes: 1000
accumulation_steps: 1
img_size: 96